#! /bin/sh

pkill dunst
dunst &

pkill sxhkd 
pgrep -x sxhkd > /dev/null || sxhkd &

pkill polybar
~/.config/polybar/launch.sh

# setxkbmap es &
pkill picom
picom & 
# --experimental-backends &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width 2
bspc config window_gap 25
bspc config top_padding 70
bspc config left_padding 10
bspc config right_padding 10
bspc config bottom_padding 10

#bspc config border_radius 20

bspc config active_border_color '#b48ead'
bspc config normal_border_color '#676a6d'
bspc config focused_border_color '#5f80bb'


bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true

bspc rule -a firefox border=on
bspc rule -a Inkscape border=on
bspc rule -a Pcmanfm follow=on
bspc rule -a Soffice follow=on
bspc rule -a Gimp follow=on
bspc rule -a Code follow=on
bspc rule -a Lxmusic state=floating follow=on
bspc rule -a XCalc state=floating rectangle=450x600+2050+940 follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tailed 

feh --bg-fill /home/h1pukema/Descargas/nord-dunas.png
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &
setxkbmap es -option caps:swapescape

pkill clipmenud
clipmenud &
xinput disable 14 && unclutter &
export QT_QPA_PLATFORMTHEME = "qt5ct"
